//
// Created by james on 2023/2/3.
//

#ifndef CPLUS_DEMO_RANDOMACCCESSFILESTRORE_H
#define CPLUS_DEMO_RANDOMACCCESSFILESTRORE_H


class RandomAcccessFileStrore {

};


#endif //CPLUS_DEMO_RANDOMACCCESSFILESTRORE_H
